name: CI/CD

on:
  push:
    branches: [main, dev]
    tags: ['v*']
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Install dependencies
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv sync
      
      - name: Run tests
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv run pytest tests/test_all_functions.py -v
      
      - name: Security check
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv run pytest tests/test_all_functions.py::test_no_subprocess_vulnerabilities -v
  
  # Publish to PyPI on version tags (optional)
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv build
          uv pip install twine
          twine upload dist/* || echo "PyPI publish skipped (no token configured)"
